version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123abc*"
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - /Users/luizmandico/dev/data:/var/lib/postgresql/data 
