spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: message-service
        uri: lb://kafka-producer
        predicates:
          - Path=/message/**

server:
  port : 8000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:20000/eureka}
      